---
creation_rules:
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age: 
        - "age1mf0f83wwjpn9q3kym0pupasuy0qdze2zhpwr2c2s8a7al082nd2qg9rhq3"
stores:
  yaml:
    indent: 2
