apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
stringData:
    secret_key: ENC[AES256_GCM,data:zXNhpRgR5gOkeG/1F9e/+L/mdfxVkGaRs3/Xc7uNdvy1pwgOackS1GIXxa+EkgkG1cBj0fot3VDEKXyD1zArv6/+oWmgOzEOyp20U0e91Fc=,iv:Egx7twIxlh2nUamH9kVxCqokDTNSoWEOIbaoW5fhzm8=,tag:f839/Y6lrOcJJ5lPPH6brg==,type:str]
    postgres_user: ENC[AES256_GCM,data:QQlpKdmbfGis,iv:FS6fphHn33mOP0d7hvLDLBwh9xIzerTTpzl3jSTQWWA=,tag:SxTqzXrYSiNrHPuvxGzC6A==,type:str]
    postgres_password: ENC[AES256_GCM,data:sZYm+gXHwkWmPinFpIwpGchaZyOwp2WVaeNWvgTCEDOyz5NiHVIEHiNcxpViK1GLrx6gpkoslEy47cS8bfEwsZ806fjdyaDuY2yu8Ihl5ec=,iv:5O2W7neSt7vrYTU/HTrH/l6fGu38CZkKknv6SzS3tJY=,tag:7uH3g7lzhEDzCBq6NKxlpQ==,type:str]
    postgres_database: ENC[AES256_GCM,data:GPppZa2qC96Y,iv:HF/b7FCc2yyv32T9TnKZtoLYrahfrTtKpnCuiRDkKUs=,tag:rCTczaxV1BEU9uzqnQSt0g==,type:str]
sops:
    age:
        - recipient: age1eq7h74807r7a5vf5uyal63xm4d879yw9ydp5sf3mx0yvquz2fywqg22sdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVUJEM01zVjYyaWJUblVs
            d3ZOZEZUVGFUZTY0Tk0xWU5yd3hFVTJ4MG44CnBHQVZ3anF0V3Zqc2xTV3ZNenY3
            WVZoSGxqOE9NSGZhYTgwSEQ0MGcxTlUKLS0tIFFCRDRkcnArNnFoMjhRc1B1anVw
            TE5jOUFscW1Wcm8xclJjdSt3QVczNEkK2u9BmOHfjvPpu8sZ2VEeYpS9yM2cL9hL
            6sIH3IPVQ+5kUBfQMEMonfPEd7kM4XEBAw8GNMX23LKc0FrJ1QrRxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T17:09:38Z"
    mac: ENC[AES256_GCM,data:MPX1VbAKcKch/WQCH/5Bsvp51300ccmMsDBeEUU1CqAp+mFNADbptuN+/2VaFj6G/xXqjZr14f1kTHcw5pNQ8c2J2LT/AVOzjOvHjfZ4pfT+Px/mcvIvlYmu+0UrNsdwDGrjCWpfUvfAgVmgOYpJrO78J+FNERfp7ktA/fd6j9Q=,iv:KLBZ6qAZ01ja8bfciALSFCfmuhGYTrKPuSfShEvFtWk=,tag:bm994rMOtyQCE+jIw3Qvmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
