---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  dependsOn:
    - name: metallb
      namespace: metallb
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    controller:
      kind: Deployment
      replicaCount: 2
      hostNetwork: false

      extraArgs:
        default-ssl-certificate: "ingress-nginx/wildcard-tls"
      ingressClassResource:
        name: nginx
        enabled: true
        default: true

      service:
        enabled: true
        type: LoadBalancer
      publishService:
        enabled: true
      admissionWebhooks:
        enabled: true
