apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: arr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/containers/prowlarr
              tag: 2.1.0
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: prowlarr.reyaan.dev
            paths:
              - path: /
                pathType: Prefix

    persistence:
      enabled: true
      existingClaim: prowlarr-data
      mountPath: /config