apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - storage.yaml
  - authentik-secrets.yml

# configMapGenerator:
#   - name: authentik-values
#     files:
#       - values.yaml

# generatorOptions:
#   disableNameSuffixHash: true