apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  chart:
    spec:
      chart: authentik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgres_password
      targetPath: authentik.postgresql.password

  values:
    server:
      ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
          - auth.reyaan.dev

    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-secrets
        secretKeys:
          passwordKey: postgres_password
        
    redis:
      enabled: true
