apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
stringData:
    secret_key: ENC[AES256_GCM,data:giU+8Vq3f4xm1bk=,iv:5gPUJH87Pc9rdLVuHps75IVJVX1jyRQhLJyPoFO2Dj4=,tag:D20BUsqHrXQoLvVJnt05iw==,type:str]
    postgres_user: ENC[AES256_GCM,data:B93sZncAR6jW,iv:hjDb+H9hNky6md4cYObveyoNx6PiNAqSpmGMftIfjOk=,tag:cvIIfrTZr2WKSToX6nEpsA==,type:str]
    postgres_password: ENC[AES256_GCM,data:q910uQsHKyMXmA==,iv:bOozEyieFMIByvT2OsY4J5+LUka9Tagg/SH9Yt7hN6g=,tag:HsTkazTCzDKV/6ZeiZOjmg==,type:str]
    postgres_database: ENC[AES256_GCM,data:OUmxEt0AgDAg,iv:fOT1VhvO66O9saOOpVkgkWGFyjeVJ4DC+8lxvduxbu0=,tag:fTXhfGWgJoXo111wiAA/Mw==,type:str]
sops:
    age:
        - recipient: age1eq7h74807r7a5vf5uyal63xm4d879yw9ydp5sf3mx0yvquz2fywqg22sdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnamdYelErSUJINUtDWTR3
            RndYVXZMaFdGSmc1MzhGV3A0Tiswc3NUSm5RCjcrNC8xZFo0L3VxRmJBOFROMno4
            bFFjQzdvaW5xaEJOeUJFRVpSaUVYSjgKLS0tIFliTHBEc2w3Z2V4bFBaZEFwNS9H
            WlJPTDBkRUJGV0FDclYzbkZmTmoyQTAKk7sIs7vLZZnvZ9PGFdq3FtJBPPkwuLOR
            Cnd4AD9w+hBYuZDLQbCQTSSmU3rN6cmmG9bvUJYKStJqDWZW62o2MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T03:15:10Z"
    mac: ENC[AES256_GCM,data:Phw2ht5nfvvrd0UIRyQbfhmMRsw1bqOXAs1pQMOrxgMnroCkFasvvehXV8WvKpVK9ROKqY1lqQtWjeBWbf1ZtzpS/tZAnv0h4Ge1vPBvj6fdjDhOiMz9niPLi0RK5Uw6j8W5feCF7B5l2kkcatqx6LE3LJ0ZZk9Z3ZTV6CRGCaI=,iv:b/Yh9SSP5R4ytiAXBJud2+1P9kDyVAoNu40K7Uke34o=,tag:lhhZoarnSl0Y9H6mj8UmKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
