apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn