apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  chart:
    spec:
      chart: authentik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m
  values:
    postgresql:
      enabled: true
    redis:
      enabled: true
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: authentik.reyaan.dev
          paths:
            - path: /
              pathType: Prefix