name: Create PR to main

on:
  workflow_run:
    workflows: ["tests", "e2e"]
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          base: main
          title: "Merge staging into main"
          body: "Automated PR created after successful tests & e2e runs."
          draft: false
          delete-branch: false