apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:o4HtLb/CKKVUZzh5XE3Nc5cyi4lssSKa45voXm+C65lvbdCGJoKRDw==,iv:I3DoZg9d7j6JOjJpAv+wE+EBBtbEdKxUOlNlP62tD7I=,tag:93qJNRq/xCo6m4LRpkwSig==,type:str]
sops:
    age:
        - recipient: age1eq7h74807r7a5vf5uyal63xm4d879yw9ydp5sf3mx0yvquz2fywqg22sdy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR3J0WVJ6K29zclhSUjNB
            L0c3MG90Q04xakpjbnF0Sks2ZFJ6dXJlMHpFClNnYjlObFNTMGJINmFrVXhWcURC
            L3QrMXFhYlZnc3d1QlVJcTRWaXF2TFkKLS0tIGJSOEJiZkRHTmR1SWxmUXlTQlF1
            VU5sUFhvekhkZEpnT3loNXZ1NXA1bXcKLDMSAYP5ZzBn9NgXDaEwDXcSqZP4VUes
            Fvhk/7gzskCA/ULM0/xIOaXnihlNWcKl9B39prcM9MQre+LeA3NP1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T17:57:51Z"
    mac: ENC[AES256_GCM,data:SU+AnXs2hNirpYlfJRIt1vIKqYgfEje2tq9bnbQhtnMsHyJOjGEsCC/uDhGOr4kWulUTqE5sAb50kxKdr8z0iMbRAFxSVaccMYUe/WXvc0iXwMsAG54XyPXZeknqdNNFIVZlZailxAbggGZImyxC5iqB5vIA0xnJ6+V8z0+MaTY=,iv:4qBUYtaqJdPo2c1wDGlGMwZcsZDyp6B+RESt0VBoBA4=,tag:CrTPG40CjigJYN1tLtKqAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
